export const GET_FUNCTION_REQUEST = "GET_FUNCTION_REQUEST"
export const GET_FUNCTION_REQUEST_SUCCESS = "GET_FUNCTION_REQUEST_SUCCESS"
export const GET_FUNCTION_REQUEST_FAILED = "GET_FUNCTION_REQUEST_FAILED"

export const GET_ALL_FUNCTIONS_REQUEST = "GET_ALL_FUNCTIONS_REQUEST"
export const GET_ALL_FUNCTIONS_REQUEST_SUCCESS = "GET_ALL_FUNCTIONS_REQUEST_SUCCESS"
export const GET_ALL_FUNCTIONS_REQUEST_FAILED = "GET_ALL_FUNCTIONS_REQUEST_FAILED"