// types for single profile
export const GET_PROFILE_REQUEST = "GET_PROFILE_REQUEST"
export const GET_PROFILE_REQUEST_SUCCESS = "GET_PROFILE_REQUEST_SUCCESS"
export const GET_PROFILE_REQUEST_FAILED = "GET_PROFILE_REQUEST_FAILED"

// types for profile creation and update
export const CREATE_OR_UPDATE_PROFILE_REQUEST = "CREATE_OR_UPDATE_PROFILE_REQUEST"
export const CREATE_OR_UPDATE_PROFILE_REQUEST_SUCCESS = "CREATE_OR_UPDATE_PROFILE_REQUEST_SUCCESS"
export const CREATE_OR_UPDATE_PROFILE_REQUEST_FAILED = "CREATE_OR_UPDATE_PROFILE_REQUEST_FAILED"


// types for all profiles
export const GET_ALL_PROFILES_REQUEST = "GET_ALL_PROFILES_REQUEST"
export const GET_ALL_PROFILES_REQUEST_SUCCESS = "GET_ALL_PROFILES_REQUEST_SUCCESS"
export const GET_ALL_PROFILES_REQUEST_FAILED = "GET_ALL_PROFILES_REQUEST_FAILED"